# Optimization Project: Biscuit Optimizer
# Roberto Basla
# Politecnico di Milano
# A.Y. 2021/2022
#
# Run file for the knapsack problem
reset;
model "src/01-knapsack/AMPL_knapsack/biscuit_knapsack.mod";
data "src/01-knapsack/AMPL_knapsack/knapsack/biscuit_knapsack.dat";
option solver 'path/to/cplex.exe';
option verbosity detailed;
solve;

display B;
display biscuit_value;
display x;
display sum{i in I} x[i];
